#!/usr/bin/env bash
cat <<"EOF"

Usage:  mlab [OPTIONS] COMMAND

Common Commands:
  key-remote           Create ssh-key and send to remote server
  first-step           Install VSCode using docker and enable to use ansible

Global Options:
  -h                   Show this message
  -v                   Print version information and quit

Run 'mlab COMMAND -h' for more information on a command.
For more details, see man mlab.

EOF
