#!/usr/bin/env bash
cat <<"EOF"
Usage: mlab [OPTIONS] COMMAND

Commands:
  cache                    Manage cache files

Options:
  -h, --help               Show this message
  -v, --version            Print version information and quit
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")

Run 'mlab COMMAND -h' for more information on a command.
For more details, see man mlab.
EOF
